### ISSUE TITLE
Using tauri-specta on tauri v2 mobile

### ISSUE THREAD

**Issue by Dreaming-Codes** [oscartbeaumont/tauri-specta#104]
I'm trying to use your awesome crate on Tauri Mobile, but I'm encountering an error when running my project on a mobile device. The issue arises because the crate attempts to save TypeScript bindings directly to my phone instead of within the project directory.

Is there a way to generate the bindings during the build process rather than at runtime to resolve this issue? Disabling bindings generation on mobile isn't a viable option for me, as my app only works on mobile.

Thank you!

**Comment by oscartbeaumont** [comment]
I suspect you could use `#[cfg(all(debug_assertions, not(target_os = "android"), not(target_os = "ios")))]` on the `.path` method [here](https://github.com/oscartbeaumont/tauri-specta/blob/9823cb6d9c4e486393e682d37c38fb6cbba7d7dd/examples/app/src-tauri/src/main.rs#L138).

All you need to do it make sure this method is not called on your mobile devices.

**Comment by oscartbeaumont** [comment]
@Brendonovich pointed out you might not also be building a desktop app which I completely missed in that original solution.

If that's the case you can setup a unit test for exporting your bindings file instead of doing within your apps runtime code.

We have an example of this in [`./examples/custom-plugin/plugin`](https://github.com/oscartbeaumont/tauri-specta/blob/9823cb6d9c4e486393e682d37c38fb6cbba7d7dd/examples/custom-plugin/plugin/src/lib.rs#L54).

**Comment by Dreaming-Codes** [comment]
Exactly what I needed

**Comment by Dreaming-Codes** [comment]
> @Brendonovich pointed out you might not also be building a desktop app which I completely missed in that original solution.
> 
> If that's the case you can setup a unit test for exporting your bindings file instead of doing within your apps runtime code.
> 
> We have an example of this in [`./examples/custom-plugin/plugin`](https://github.com/oscartbeaumont/tauri-specta/blob/9823cb6d9c4e486393e682d37c38fb6cbba7d7dd/examples/custom-plugin/plugin/src/lib.rs#L54).

Exactly what I needed, thanks
