### ISSUE TITLE
[question] Optional Types?

### ISSUE THREAD

**Issue by melMass** [oscartbeaumont/tauri-specta#14]
Hi, 

Thanks for this great plugin, is there a way to generate `Option<T>` types as `?` optionals in TS?

Thanks

**Comment by Brendonovich** [comment]
You can do that by adding `#[specta(optional)]` to the field you want to be optional. If you haven't checked out the [Specta documentation](https://docs.rs/specta/latest/specta/) I'd suggest doing so, since this question isn't relevant to Tauri Specta specifically, but it looks like we don't actually document `#[specta(optional)]` yet.

**Comment by melMass** [comment]
Oh awesome thanks
