### ISSUE TITLE
`mut` keyword included in command argument

### ISSUE THREAD

**Issue by probablykasper** [oscartbeaumont/tauri-specta#24]
This command:
```rs
#[command]
#[specta::specta]
pub async fn new_group(mut group: Group) {}
```
gets this binding:
```ts
export function newGroup(mutGroup: Group) {
    return invoke<Group[]>("new_group", { mutGroup })
}
```

**Comment by Brendonovich** [comment]
hmmm i'm guessing this is a problem with `specta::specta`

**Comment by oscartbeaumont** [comment]
@probablykasper Good spot, this brings up a bigger issue of how we handle Rust destructuring in function args but for now, I am going to forbid that because I think fixing it will be a breaking change in Specta and it's not gonna be long until we do v2 with other breaking changes anyway.

This should be fixed with the latest Specta release if you pull it into your project.

**Comment by probablykasper** [comment]
Awesome, it works perfectly now! Thank you !!
