### ISSUE TITLE
Build-time type generation

### ISSUE THREAD

**Issue by D3PSI** [oscartbeaumont/tauri-specta#27]
Hi,

does tauri-specta support build-time generation of types? generating them at runtime seems... sketchy, and requires a development build and run of that development build before a production build in order to guarantee typesafety. is there any way around this (via build-time generation of types for example)?

cheers & thanks

**Comment by Brendonovich** [comment]
If by build-time you mean without compiling your app first, then no. If by build-time you mean without running the app, then yes. You can do the type exporting in a unit test which can run independently of your app, but when you have to build most of the code to get the types to export anyway, you may as well just build + run your app to get the types generated.
Not sure if you're doing this already but checking the generated types into git can be helpful. They're not crazy big and being in git means you only have to generate them once after making changes.

**Comment by oscartbeaumont** [comment]
I intend to look into a way to make the Specta trait impls automatically removable for production builds in the future but it's tough because I need to account for the way rspc works and it always needs to depend on Specta's traits or you could get into invalid situations.

I have an issue [here](https://github.com/oscartbeaumont/specta/issues/20) around my oiginal idea about this although I am not certain if that idea will work cause it brings up a lot of weird edge cases with external crates that also do Specta impls.

It's also worth noting that can you can kinda do this already but its DX is suboptimal. This will conditionally enable the Specta macro in test and development builds. Using a unit test for type exporting is fairly common with Specta based libraries and is generally recommended because type exporting can fail and you will wanna catch it before production.
```rust
#[derive(Debug, Clone)]
#[cfg_attr(any(test, debug_assertions), derive(specta::Type))] // Specta impls will only exist for debug or test builds
#[cfg_attr(any(test, debug_assertions), specta(transparent))] // You also need to be conditional on Specta attributes but generally just use Serde ones so it's not a problem if serde's macros are always enabled.
pub struct PeerId(
	pub(crate)  libp2p::PeerId,
);

fn main() {
  #[cfg(any(test, debug_assertions))]
  // TODO: Export the types
}
```

I personally dislike the idea of a static-analysis based type exporter because it just can't be as smart as a runtime system as it's gotta guess the types as opposed to being told what they are. Eg. `{ 32 }` what type is this? It could really be any number type and Rust will a lot of time infer it from where it's used (shown in the image below). It's definitely a tradeoff though.
![image](https://github.com/oscartbeaumont/tauri-specta/assets/21004798/c9e45519-b134-49a1-846a-ba07104f11e6)

**Comment by D3PSI** [comment]
thank you both for your detailed responses. i'd like to clarify my current situation.

> If by build-time you mean without compiling your app first, then no. If by build-time you mean without running the app, then yes. You can do the type exporting in a unit test which can run independently of your app, but when you have to build most of the code to get the types to export anyway, you may as well just build + run your app to get the types generated.

by build-time i mean without running the app. of course you need to compile the app first in order to validate your rust types. what i am doing right now is, i have introduced a command line flag in the tauri backend code, `--generate-bindings-only`, and when i run the backend code with this flag it essentially only executes `tauri_specta::ts::export()` and thus writes my typescript definitions into the defined file and exits. essentially analogous to what you're telling me to do with a unit test. however, this now means that i have to build & run the tauri backend with this flag on my local for development as well as in my github actions before creating a production build and bundling the app for release. if there was any way to generate the typescript definitions at build-time i could avoid having to run the app with this flag (or running a unit test for that matter, as per your suggestion).

>Not sure if you're doing this already but checking the generated types into git can be helpful. They're not crazy big and being in git means you only have to generate them once after making changes.

of course that could work, and in an ideal world it would. however, let's put it this way, developers are only humans and everything that has to be run manually before creating a commit is dangerous and can easily be forgotten and is hence a bit of a nuisance. of course you could argue that you can introduce a git pre-commit hook to somehow generate those types, but that just shifts the problem as git hooks need to be manually configured by each local clone of the repository.

a perfect solution in my eyes is what the [`tsify`](https://github.com/madonoharu/tsify) crate has got going on - i don't know how they do it, or what the tradeoff/differences to specta are, but if you just run a build when using `tsify` you don't have to separately run your application to get the type definitions output into the types file.

---

>Using a unit test for type exporting is fairly common with Specta based libraries and is generally recommended because type exporting can fail and you will wanna catch it before production.

am i correctly reading from this that my approach as described above is the recommended way at the current moment?

>I personally dislike the idea of a static-analysis based type exporter because it just can't be as smart as a runtime system as it's gotta guess the types as opposed to being told what they are. Eg. { 32 } what type is this? It could really be any number type and Rust will a lot of time infer it from where it's used (shown in the image below). It's definitely a tradeoff though.

i understand now, thank you. so type inference et al. are the important tradeoffs to consider here, and i guess we can therefore not get around a runtime solution. thank you for the explanation!

i am taking away from this exchange that what i am looking for currently is not possible, and that the way i am currently doing this is the recommended way (or analogous to the recommended way), is that correct?

thank you both for your time and your detailed responses into my inquiry.

**Comment by Brendonovich** [comment]
> developers are only humans and everything that has to be run manually before creating a commit is dangerous

That's why we also recommend doing the type generation as part of your app's startup - unless a dev switches to another branch, runs the app, switches back, and commits without re-running the app, you're naturally going to have correct types.

>  i don't know how they do it, or what the tradeoff/differences to specta are, but if you just run a build when using tsify you don't have to separately run your application to get the type definitions output into the types file.

Tsify is able to do this bc they use a special aspect of `wasm-bindgen` and generate TS at macro expansion time:
<img width="576" alt="image" src="https://github.com/oscartbeaumont/tauri-specta/assets/14191578/82b078a8-febc-4ba6-9f20-f9867088f16d">
It's just a step up from static analysis like Typeshare.
