### ISSUE TITLE
Should object/array function arguments be marked `readonly`?

### ISSUE THREAD

**Issue by mon** [oscartbeaumont/tauri-specta#30]
I'm not _amazing_ at typescript, but I'm running into an issue where I have a list of strings that are const so I can generate container types for them:
```ts
  const FILTER_KEYS = ["a","b","c"] as const;
```

If a specta-generated invoke needs a `string[]` argument, this needs a cast because Typescript can't guarantee it isn't mutated. But because `invoke` just serialises, I think it should be fine to add `readonly` to any list arguments (and potentially object arguments too).

**Comment by Brendonovich** [comment]
Technically this is true, but I'm not sure it's worth it.

1. In my experience, having `readonly` data isn't very common
2. Doing this _properly_ would involve applying `readonly` to all types, not just argument types.
  `Readonly<T>` exists, but it doesn't apply to nested objects, which would cause this to break down if there was a nested object expecting a `string[]`.
  Making all generated object fields `readonly` is out of the question since using generated types in places where data is mutated is fairly common.

**Comment by mon** [comment]
Ah, the subtleties of nested objects wasn't something I'd thought about. Way too much effort to implement, and I think `[...FILTER_KEYS]` is fine. Thanks!
