### ISSUE TITLE
Support adding types that are not used in a command or event

### ISSUE THREAD

**Issue by nobane** [oscartbeaumont/tauri-specta#74]
There should be an easy way to add structs that have `specta::Type`, but are not referenced in a command or event, to the generated output.

**Comment by Brendonovich** [comment]
this applies to rspc too really, perhaps specta should have a trait that types which collect specta information

**Comment by oscartbeaumont** [comment]
I recon Specta needs a builder-style API for collecting types, we could potentially use that for this too.

I think I was thinking something like:
```rust
TypeCollector::new()
   .type::<A>()
   .type::<B>();
```
I went looking for the GH issue on the Specta repo but can't find it.

**Comment by Brendonovich** [comment]
The builder would be good, but we need to keep in mind that for tauri-specta and rspc we need to ensure that ownership of the builder is ultimately held by the package-specific builders, since they take control of the exporting process, hence why i suggested a trait for this rather than exposing the underlying type collection.

**Comment by oscartbeaumont** [comment]
This will be in the next release which will hopefully land within the next week once the bugs in #86 are sorted out.

[docs here](https://github.com/oscartbeaumont/tauri-specta/blob/main/docs/v2.md#extra-types)
