### ISSUE TITLE
Question: is it possible to support generics for the event? 

### ISSUE THREAD

**Issue by kwonoj** [oscartbeaumont/tauri-specta#79]
In a simple example like the one below

```
#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
pub struct SomeEvent<T> {
    kind: String,
    payload: T,
}
```

When you build, you'll see an error message like this.

```
17 | pub struct SomeEvent<T> {
   |            ^^^^^^^^^ expected 1 generic argument
   |
note: struct defined here, with 1 generic parameter: `T`
```

The Event macro doesn't seem to be supporting the struct for generic type, I was wondering if this is known limitation of adjusting macro will make things work.

**Comment by Brendonovich** [comment]
Most likely no, since it doesn't really make sense - how is Tauri supposed to know the type of `T` to serialize/deserialize?
Tauri can emit a `SomeEvent<i32>` and `SomeEvent<String>`, but to emit `SomeEvent<T>` it would need to know how to serialize `T` ahead of time.

There's some alternative approaches I can see being more useful here:
1. You want to put arbitrary data in `payload`. Use `serde_json::Value` and remove the generic.
2. You want different values of `T` to be different events. Create wrapper structs like `SomeEventInt(SomeEvent<i32>)` and `SomeEventString(SomeEvent<String>)` that implement `Event`, and remove it from `SomeEvent`
3. You want `payload` to be one of a few predetermined types. Make a `SomeEventPayload` enum where each type is a different variant.
